# Generated by Django 3.2 on 2022-11-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(blank=True, upload_to='sign_lang/model')),
                ('type', models.CharField(choices=[('CNN', 'cnn'), ('DNN', 'dnn'), ('RandomForest', 'rf'), ('KNN', 'knn'), ('SGD', 'sgd'), ('XGB', 'xgb')], default='CNN', max_length=12)),
                ('version', models.CharField(max_length=10)),
                ('comment', models.CharField(default=' ', max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250, verbose_name='제목')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('text', models.CharField(max_length=250, verbose_name='번역')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250, verbose_name='제목')),
                ('image', models.ImageField(upload_to='images/')),
                ('label', models.CharField(choices=[(65, 'A'), (66, 'B'), (67, 'C'), (68, 'D'), (69, 'E'), (70, 'F'), (71, 'G'), (72, 'H'), (73, 'I'), (74, 'J'), (75, 'K'), (76, 'L'), (77, 'M'), (78, 'N'), (79, 'O'), (80, 'P'), (81, 'Q'), (82, 'R'), (83, 'S'), (84, 'T'), (85, 'U'), (86, 'V'), (87, 'W'), (88, 'X'), (89, 'Y'), (90, 'Z')], default='A', max_length=2, verbose_name='번역')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', models.IntegerField(default=0, verbose_name='정답여부')),
                ('version', models.ForeignKey(db_column='version', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='versionR', to='sign_lang.model')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
