# Generated by Django 3.2 on 2022-11-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_lang', '0002_auto_20221122_0603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
